name: Build whisper.wasm demo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      # Konfiguracja z KATALOGU GŁÓWNEGO repo (nie z examples/)
      - name: Configure (emcmake)
        run: |
          emcmake cmake -S . -B build-wasm \
            -DWHISPER_WASM=ON \
            -DGGML_WASM=ON \
            -DGGML_WASM_SIMD=ON

      # Budujemy KONKRETNY target: whisper.wasm
      - name: Build target
        run: cmake --build build-wasm -j 4 --target whisper.wasm

      # Zbieramy pliki wygenerowane przez przykład
      - name: Collect demo files
        run: |
          mkdir -p dist
          # Spróbuj typowych lokalizacji w buildzie
          for p in \
            "build-wasm/bin/whisper.wasm" \
            "build-wasm/examples/whisper.wasm/whisper.wasm" \
            "build-wasm/whisper.wasm/whisper.wasm"
          do
            [ -f "$p" ] && cp -v "$p" dist/whisper.wasm
          done

          for p in \
            "build-wasm/examples/whisper.wasm/main.js" \
            "build-wasm/whisper.wasm/main.js" \
            "examples/whisper.wasm/main.js"
          do
            [ -f "$p" ] && cp -v "$p" dist/main.js
          done

          for p in \
            "build-wasm/examples/whisper.wasm/index.html" \
            "build-wasm/whisper.wasm/index.html"
          do
            [ -f "$p" ] && cp -v "$p" dist/index.html
          done

          # Awaryjnie użyj szablonu, jeśli index.html nie powstał
          [ -f dist/index.html ] || cp -v examples/whisper.wasm/index-tmpl.html dist/index.html

          ls -la dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: whisper-wasm-demo
          path: dist/*

