name: Build whisper.wasm demo
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Uwaga: najnowszy master NIE ma już targetu 'whisper.wasm'.
        # Jeśli chcesz koniecznie stary przykład 'examples/whisper.wasm',
        # ustaw tu konkretne SHA z historii, w którym on istniał:
        # with:
        #   ref: <WSTAW_SHA_Z_HISTORII>

      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      # Konfiguracja z katalogu głównego
      - name: Configure (emcmake)
        run: |
          emcmake cmake -S . -B build-wasm \
            -DGGML_WASM=ON \
            -DGGML_WASM_SIMD=ON

      # ⚠️ Jeżeli budujesz NAJNOWSZY master, nie ma targetu 'whisper.wasm'
      # (dlatego poprzedni run krzyczał: "No rule to make target 'whisper.wasm'")
      # Wtedy ten krok można tymczasowo pominąć lub zbudować inne web-targety GGML.
      # Jeśli podepniesz stare SHA z przykładem whisper.wasm, to odkomentuj:
      # - name: Build whisper.wasm
      #   run: cmake --build build-wasm -j 4 --target whisper.wasm

      # Zbieranie plików demo (zależnie od wersji repo mogą być w różnych miejscach)
      - name: Collect demo files (best-effort)
        run: |
          mkdir -p dist
          # whisper.wasm + main.js + index.html – tylko gdy istnieją (stare SHA)
          for p in \
            build-wasm/bin/whisper.wasm \
            build-wasm/examples/whisper.wasm/whisper.wasm \
            build-wasm/whisper.wasm/whisper.wasm
          do
            [ -f "$p" ] && cp -v "$p" dist/whisper.wasm
          done
          for p in \
            build-wasm/examples/whisper.wasm/main.js \
            build-wasm/whisper.wasm/main.js \
            examples/whisper.wasm/main.js
          do
            [ -f "$p" ] && cp -v "$p" dist/main.js
          done
          for p in \
            build-wasm/examples/whisper.wasm/index.html \
            build-wasm/whisper.wasm/index.html
          do
            [ -f "$p" ] && cp -v "$p" dist/index.html
          done
          [ -f dist/index.html ] || ( [ -f examples/whisper.wasm/index-tmpl.html ] && cp -v examples/whisper.wasm/index-tmpl.html dist/index.html || true )
          ls -la dist || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: whisper-wasm-demo
          path: dist/*
